sequenceDiagram
    participant User
    participant Gateway
    participant Edge
    participant Portal
    participant Platform
    Gateway->>Gateway: Power On
    Gateway->>Edge: Service Mgmt: Start Edge
    Edge->>Edge: Enter Mode: PROVISIONING
    User->>Portal: Press 'Provision'
    Edge->>Platform: Create developer, system, user, edge, retarget
    Edge->>Edge: Enters RUNTIME mode, and autosync begins